environment: "staging"

tiler:
  enabled: true
  image:
    # e.g. myacr.azurecr.io/my-repository
    repository: ""
    pullPolicy: Always
    tag: "latest"

  server:
    maxWorkers: "1"
    minDbConnections: "1"
    maxDbConnections: "1"
    workersPerCore: "1"
    webConcurrency: "1"

  service:
    type: ClusterIP
    port: 80
    annotations: {}

  deploy:
    replicaCount: 10
    podAnnotations: {}
    imagePullSecrets: []
    securityContext: {}
    podSecurityContext: {}
    resources: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}
    autoscaling:
      enabled: false

  stac_api_url: ""
  stac_api_href: ""
  pc_sdk_sas_url: ""

  host: "0.0.0.0"
  port: "80"
  appRootPath: ""

postgres:
  serverName: ""
  user: ""
  password: ""
  dbName: "postgis"
  port: "5432"

metrics:
  instrumentationKey: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

nameOverride: ""
fullnameOverride: ""
